name: Run Tests (Go)

on: push

permissions:
  contents: read

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.33.0'

      - name: Run Tests
        run: |
          go install gotest.tools/gotestsum@latest
          make test

      - name: Generate coverage report
        if: always()
        uses: mridang/action-test-reporter@v3
        with:
          results-path: '.out/junit.xml'
          coverage-path: '.out/lcov.info'
